// <auto-generated />
namespace swop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FixToUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixToUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202008301230180_FixToUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
